### ISSUE TITLE
Making no changes to a measurment removes it

### ISSUE THREAD

**Issue by Zumux** [QuantumPhysique/trale#107]
**Describe the bug**
Editing a measurement and then not changing anything and saving it removes it and says  "Adding measurement was skipped. Measurement exists already." 

**To Reproduce**
1. Go to edit a measurement
2. Change nothing
3. And press save

**Expected behavior**
It saves and changes nothing

**User Information (please complete the following information):**
 - Device: Pixel 6a
 - OS: GrapheneOS 14
 - Version:  v0.7.0
 - Downloaded: Github

**Comment by braniii** [comment]
@Zumux thx for opening this issue. I guess I've messed up there, this shouldn't happen.

**Comment by gwosd** [comment]
@Zumux Thx for reporting the bug. It should be fixed in the latest version [v0.7.1](https://github.com/QuantumPhysique/trale/releases/tag/v0.7.1).
