### ISSUE TITLE
Allow goal weight under 110lb, maybe up to 100lb?

### ISSUE THREAD

**Issue by SaturnsGlaive** [QuantumPhysique/trale#114]
**Describe the bug**
I am just under 5 feet/151cm tall. A healthy weight for a female of my age and my height is anywhere between 95lb-128lb. My goal weight is 105lb. I feel this should be an acceptable weight goal in the app.

**To Reproduce**
1. Be me, 151cm tall
2. Add goal weight of 105lb
3. Get message saying the app won't accept any goal weight below 110lb

**Expected behavior**
App should accept lower goal weight.

I will note that I do appreciate the message about anorexia, it's very thoughtful. However the weight difference of 5lb from 110lb to 105lb feels like a world of a difference on my short frame. Because I am so short, every pound counts.

Thank you!

**Comment by SaturnsGlaive** [comment]
Oops just realized there is a dupe issue. I did not check for the kg equivalent of this bug haha :)

https://github.com/QuantumPhysique/trale/issues/32

**Comment by braniii** [comment]
Hi @SaturnsGlaive, thx a lot for opening this issue. And I see your point, however I am also concerned about anorexia. Would it be fine for you if we add the possibility of adding a height, which then defines the minimal weight via the bmi index?
