### ISSUE TITLE
imperial units recorded incorrectly

### ISSUE THREAD

**Issue by carryforward** [QuantumPhysique/trale#12]
I set the units in the settings tab to lbs, then I save a new datapoint.  The datapoint weight that is saved is 2.2045 times the entered weight.

**Comment by braniii** [comment]
@carryforward thank you for pointing out this bug. I have to admit that we have added this feature, but then changed some internal APIs without checking if different units still work.
This will be fixed with the next release.

**Comment by gwosd** [comment]
The bug should be fixed in the upcoming version v0.4.5.
It is available on github or in a few days on Fdroid. If the bug persists or in case you find another one, feel free to reopen this issue or open a new one, respectively.
