### ISSUE TITLE
Show the time of the measurement in the measurement list

### ISSUE THREAD

**Issue by Zumux** [QuantumPhysique/trale#123]

**Comment by braniii** [comment]
Hi @Zumux thank you for opening this issue.
@gwosd Actually to make the list look more modern, we could group the measurements by year (and month :thinking: ) so that there is less redundant text. What is your opinion on that idea?

**Comment by gwosd** [comment]
@Zumux Thanks for your feedback!
@braniii Sounds great! :)

**Comment by braniii** [comment]
This feature will be added in the upcoming version v0.8.0
