### ISSUE TITLE
Add project to weblate

### ISSUE THREAD

**Issue by braniii** [QuantumPhysique/trale#14]
https://hosted.weblate.org/

**Comment by braniii** [comment]
@gwosd I have applied for a libre plan at https://hosted.weblate.org/projects/trale/localizations/

<a href="https://hosted.weblate.org/engage/trale/">
<img src="https://hosted.weblate.org/widget/trale/localizations/multi-auto.svg" alt="Translation status" />
</a>

**Comment by comradekingu** [comment]
Making it specifically AGPLv3-**only** for the translations may not be desirable.
It is easier to maintain compatibility with current and future licenses with the "or later".
Can be changed in
https://hosted.weblate.org/settings/trale/localizations/
and
https://hosted.weblate.org/settings/trale/glossary/

**Comment by braniii** [comment]
@comradekingu thank you for your advice. Is AGPLv3 in general not suitable, or only to fix it to version 3?

PS: thx for adding your translation :)

**Comment by comradekingu** [comment]
@braniii
The "-or later" (as opposed to "-only") allows going to a potential AGPLv4 once released,
without asking all individual contributors.

**Comment by braniii** [comment]
> @braniii
> The "-or later" (as opposed to "-only") allows going to a potential AGPLv4 once released,
> without asking all individual contributors.

I have changed the license.
