### ISSUE TITLE
Import the file (freezing)

### ISSUE THREAD

**Issue by SophieZero** [QuantumPhysique/trale#19]
Hi, I discovered Trale today in F-Droid and immediately felt that this is the app I've been looking for. I encountered an issue while trying to import my past weight records. Could you please help me?

I've been recording my weight since 2020, and I'd like to import it into the app.

(1) I created several records in the app and exported them to a txt file.
(2) I modified/added other records on my laptop and attempted to import them into the app. However, the app is freezing.

I tested it with both "Z Flip 5" and "Galaxy S9." Both phones have the same phenomenon: the app cannot import the txt file, showing the black screen (freezing).

I'm attaching the txt file that I created.
(This file was deleted to protect your privacy @SophieZero, but thank you for providing.)

I would be grateful if you could check into this issue. Thank you so much in advance!

**Comment by gwosd** [comment]
Hi, thank you very much :)

I think the reason for the freeze is the not optimized data interpolation (it scales poorly with the total time span) and a not optimal import function.

The former is currently being addressed in the following  #15.
In addition, I will improve the import function in the next few days.

In the meantime, you can import the data with Caffeine (or just tap the screen to keep it awake) and a little patience. It should take less than 5min.

**Comment by gwosd** [comment]
Remark, in case of a Pixel 7, the import of your data took roughly 1 minute. With the improved import function in the new version [v0.4.7](https://github.com/QuantumPhysique/trale/tag/v0.4.6) it was only a few seconds.

The new version v0.4.7 is available on GitHub, and should be also available on F-Droid in a few days. 
In case you still have problems importing your data or in case you find another bug, feel free to reopen this issue or open a new one, respectively :)

**Comment by SophieZero** [comment]
I imported my data successfully! Thank you so much!!
