### ISSUE TITLE
🇵🇱 Polish translations

### ISSUE THREAD

**Issue by piotr-marendowski** [QuantumPhysique/trale#21]
# This issue tracks maintenance and possible issues with Polish translation.

Hi! I translated the app to Polish, and would like to be a maintainer of Polish translation of this app. Thanks.

**Comment by comradekingu** [comment]
You can go through the recent translations for Polish here
https://hosted.weblate.org/changes/browse/trale/localizations/pl/
:)

**Comment by braniii** [comment]
Weblate is now setup and you can simply adjust the translations from the web ui. The only thing is, that trale is still not accepted for the free tier.
