### ISSUE TITLE
Interpolation

### ISSUE THREAD

**Issue by alabotski** [QuantumPhysique/trale#25]
When I choose first interpolation
just a gray background is displayed

[Screenshot_20240122-065521](https://github.com/QuantumPhysique/trale/assets/439337/2519bf5c-a6ac-4ff5-8ee3-35bc2ad2e576)
[Screenshot_20240122-065530](https://github.com/QuantumPhysique/trale/assets/439337/b6968e99-8662-428f-bf9b-5b8dae711119)

If you choose between 2-4 switches, the graph is displayed normally

[Screenshot_20240122-065548](https://github.com/QuantumPhysique/trale/assets/439337/60293382-5a0a-4cba-82cc-7d986aade1cf)

**Comment by braniii** [comment]
Hi, thank you for reporting this issue. Which version are you using? I have tried it on 2 different versions and in one case only the interpolation was missing. But anyhow, in #15 I am currently rewritting the interpolation logic. So I will ensure to fix this bug as well.

And just as a short remark: The first case corresponds to no interpolation and therefore the extrapolation predictions are not meaningful.

**Comment by gwosd** [comment]
@braniii As the prediction in the 'no interpolation' case is not meaningful, I would suggest removing the prediction panel for this case.

**Comment by alabotski** [comment]
@braniii hi
0.4.6

It's my backup

[trale_2024-01-22.txt](https://github.com/QuantumPhysique/trale/files/14011957/trale_2024-01-22.txt)
