### ISSUE TITLE
App won't start after several entries

### ISSUE THREAD

**Issue by ni720** [QuantumPhysique/trale#80]
My trale wont start anymore after entering 3 or 4 measurements. It completely hangs on a loading animation.

1. Start trale for the first time after install
2. enter 3 or 4 measurements with for example one month apart and increasing weight.
3. close app
4. Start app again, it will hang

**User Information (please complete the following information):**
 - Device: oneplus 7pro
 - OS: lineageos-microg 20
 - Version: 0.6.1
 - Downloaded: F-Droid
![signal-2024-04-17-13-41-17-721](https://github.com/QuantumPhysique/trale/assets/5901728/de8ef403-28d5-4560-80e3-831eb00203c8)
![signal-2024-04-17-13-41-56-843](https://github.com/QuantumPhysique/trale/assets/5901728/54f5bc4b-a041-4dba-85c5-87c2644a3b09)
[trale_2024-04-17.txt](https://github.com/QuantumPhysique/trale/files/15010404/trale_2024-04-17.txt)

**Comment by gwosd** [comment]
Hi, sorry for the inconvenience! 

This bug is most likely related to #65 and #70. Could you please install the latest version 0.6.2 from the F-Droid store to see if this fixes the problem?
