### ISSUE TITLE
Default language is set to Czech

### ISSUE THREAD

**Issue by Eialidesse** [QuantumPhysique/trale#84]
-When i launched the app first time, it was in czech language. Because i use my phone with french language but the app doesn't recognize it. So i figured out that the default language of the app is czech. You should replace it with english. And the app supports even norwegian but no french. That's weird.

-Also, i want to see my body mass index on the application. But this feature isn't supported by the app for now.

**Comment by dekonnection** [comment]
I discovered this app today.

Seeing that french was missing I just added it to Weblate and translated all strings 🙂

**Comment by braniii** [comment]
@dekonnection thx for the translation :) I'll try to push an update soonish.

@Eialidesse the app supports English and German only, the languages the maintainer speaks. All other languages were contributed by the community. You are the first user to report that the default language was Czech, and true this sounds like a bug. Can you please tell me which language is set on your phone and what  which is selected in the app settings.

And regarding the second issue, this is related to #32. On the long run, we are planning to support the bmi.
